minio:
 url: http://minio-svc:9000
 access-key: v6rWvVtfNmrabacZQmQd
 secret-key: 1JlXFUqvFED0erOHiAgPPcEz4NJdzn3ZHZNsff8a
 bucketName: belajar-backend
spring:
 servlet:
  multipart:
   max-file-size: -1
   max-request-size: -1
 application:
  name: booking
 datasource:
  url: jdbc:postgresql://postgres-svc:5433/booking
  username: postgres
  password: postgres
  driver-class-name: org.postgresql.Driver
  hikari:
    maximum-pool-size: 10
    minimum-idle: 5
    idle-timeout: 30000
    connection-timeout: 30000
    max-lifetime: 600000
 jpa:
  database: POSTGRESQL
  hibernate:
    ddl-auto: validate
  properties:
    hibernate:
      format_sql: true
  show-sql: true
 flyway:
  url: jdbc:postgresql://postgres-svc:5433/booking
  user: postgres
  password: postgres
  enabled: true
  baseline-on-migrate: true
  locations: classpath:db/migration
server:
 port: 8080

---
spring:
 config.activate.on-profile: test
 datasource.url: jdbc:postgresql://postgres-svc:5433/booking
 jpa.hibernate.ddl-auto: validate
