spring:
 application:
  name: booking
 datasource:
  url: jdbc:postgresql://localhost:5432/booking
  username: postgres
  password: postgres
  driver-class-name: org.postgresql.Driver
  hikari:
    maximum-pool-size: 10
    minimum-idle: 5
    idle-timeout: 30000
    connection-timeout: 30000
    max-lifetime: 600000
 jpa:
  database: POSTGRESQL
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
  show-sql: true
server:
 port: 8080

---
spring:
 config.activate.on-profile: test
 datasource.url: jdbc:postgresql://localhost:5432/booking_test
 jpa.hibernate.ddl-auto: create
